# AGENTS.md — {{project}}

> Generated by Solo Founder Agent OS. Manual project-specific instructions may be added outside `SFO` controlled blocks.

## Read order

1. This file.
2. `CLAUDE.md` if present.
3. `.cursor/rules/agent-workflow.mdc` if using Cursor.
4. `.claude/commands/*` if using Claude Code.

{{rules_bundle}}

## Project Overrides

Protected files:
{{protected_files}}

Forbidden patterns:
{{forbidden}}

Checks:
{{checks}}

## Final rule

When ambiguous, ask before changing architecture, protected files, data model, auth, billing, deployment or generated files.
